name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Show Repository Files
        run: |
          pwd
          ls -la
          find .

      - name: Build Image
        run: docker build -t cloudforge-web .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Successful
        run: echo "Application deployed"